name: smart_recruitment_flutter_user
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smart_recruitment_core:
    git:
      url: https://gitlab.com/ehsan.ab101/smart_recruitment_flutter_core.git
      ref: master

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter_local_notifications: ^17.0.0
  easy_localization: ^3.0.5
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/svg/
    - assets/images/jpg/
    - assets/translation/
    - assets/images/svg/camera.svg
  uses-material-design: true
