// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOJ9HfQEgXTsEOlsMHqwuiBRLaSH7Qdok',
    appId: '1:640262866764:web:2f4a110976dd845682b1e9',
    messagingSenderId: '640262866764',
    projectId: 'go-resume-30a5c',
    authDomain: 'go-resume-30a5c.firebaseapp.com',
    storageBucket: 'go-resume-30a5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4-cpAaGOV8nY-EMiz068C1IFFttfvqQ',
    appId: '1:640262866764:android:9195459b8f6ce7b882b1e9',
    messagingSenderId: '640262866764',
    projectId: 'go-resume-30a5c',
    storageBucket: 'go-resume-30a5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pOXwqE5ZyrxoKCoPvPPS5EbSSan-990',
    appId: '1:640262866764:ios:995b505edc25e57382b1e9',
    messagingSenderId: '640262866764',
    projectId: 'go-resume-30a5c',
    storageBucket: 'go-resume-30a5c.appspot.com',
    iosBundleId: 'com.example.smartRecruitmentFlutterUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pOXwqE5ZyrxoKCoPvPPS5EbSSan-990',
    appId: '1:640262866764:ios:995b505edc25e57382b1e9',
    messagingSenderId: '640262866764',
    projectId: 'go-resume-30a5c',
    storageBucket: 'go-resume-30a5c.appspot.com',
    iosBundleId: 'com.example.smartRecruitmentFlutterUser',
  );
}
